# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.2.4
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from permify_async.models.v1alpha1_type import V1alpha1Type

class TestV1alpha1Type(unittest.TestCase):
    """V1alpha1Type unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1Type:
        """Test V1alpha1Type
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1Type`
        """
        model = V1alpha1Type()
        if include_optional:
            return V1alpha1Type(
                dyn = permify_async.models.dyn.dyn(),
                null = '',
                primitive = 'PRIMITIVE_TYPE_UNSPECIFIED',
                wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED',
                well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED',
                list_type = permify_async.models.list_type.ListType(
                    elem_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                        dyn = permify_async.models.dyn.dyn(), 
                        null = '', 
                        primitive = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED', 
                        map_type = permify_async.models.map_type.MapType(
                            key_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                                dyn = permify_async.models.dyn.dyn(), 
                                null = '', 
                                function = permify_async.models.function_type.FunctionType(
                                    result_type = , 
                                    arg_types = [
                                        
                                        ], ), 
                                message_type = '', 
                                type_param = '', 
                                type = , 
                                error = permify_async.models.error.error(), 
                                abstract_type = permify_async.models.abstract_type.AbstractType(
                                    name = '', 
                                    parameter_types = [
                                        
                                        ], ), ), 
                            value_type = , ), 
                        function = permify_async.models.function_type.FunctionType(), 
                        message_type = '', 
                        type_param = '', 
                        type = , 
                        error = permify_async.models.error.error(), 
                        abstract_type = permify_async.models.abstract_type.AbstractType(
                            name = '', ), ), ),
                map_type = permify_async.models.map_type.MapType(
                    key_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                        dyn = permify_async.models.dyn.dyn(), 
                        null = '', 
                        primitive = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED', 
                        list_type = permify_async.models.list_type.ListType(
                            elem_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                                dyn = permify_async.models.dyn.dyn(), 
                                null = '', 
                                function = permify_async.models.function_type.FunctionType(
                                    result_type = , 
                                    arg_types = [
                                        
                                        ], ), 
                                message_type = '', 
                                type_param = '', 
                                type = , 
                                error = permify_async.models.error.error(), 
                                abstract_type = permify_async.models.abstract_type.AbstractType(
                                    name = '', 
                                    parameter_types = [
                                        
                                        ], ), ), ), 
                        function = permify_async.models.function_type.FunctionType(), 
                        message_type = '', 
                        type_param = '', 
                        type = , 
                        error = permify_async.models.error.error(), 
                        abstract_type = permify_async.models.abstract_type.AbstractType(
                            name = '', ), ), 
                    value_type = , ),
                function = permify_async.models.function_type.FunctionType(
                    result_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                        dyn = permify_async.models.dyn.dyn(), 
                        null = '', 
                        primitive = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                        well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED', 
                        list_type = permify_async.models.list_type.ListType(
                            elem_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                                dyn = permify_async.models.dyn.dyn(), 
                                null = '', 
                                map_type = permify_async.models.map_type.MapType(
                                    key_type = , 
                                    value_type = , ), 
                                message_type = '', 
                                type_param = '', 
                                type = , 
                                error = permify_async.models.error.error(), 
                                abstract_type = permify_async.models.abstract_type.AbstractType(
                                    name = '', 
                                    parameter_types = [
                                        
                                        ], ), ), ), 
                        map_type = permify_async.models.map_type.MapType(), 
                        message_type = '', 
                        type_param = '', 
                        type = , 
                        error = permify_async.models.error.error(), 
                        abstract_type = permify_async.models.abstract_type.AbstractType(
                            name = '', ), ), 
                    arg_types = [
                        
                        ], ),
                message_type = '',
                type_param = '',
                type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                    dyn = permify_async.models.dyn.dyn(), 
                    null = '', 
                    primitive = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                    wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                    well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED', 
                    list_type = permify_async.models.list_type.ListType(
                        elem_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                            dyn = permify_async.models.dyn.dyn(), 
                            null = '', 
                            map_type = permify_async.models.map_type.MapType(
                                key_type = , 
                                value_type = , ), 
                            function = permify_async.models.function_type.FunctionType(
                                result_type = , 
                                arg_types = [
                                    
                                    ], ), 
                            message_type = '', 
                            type_param = '', 
                            error = permify_async.models.error.error(), 
                            abstract_type = permify_async.models.abstract_type.AbstractType(
                                name = '', 
                                parameter_types = [
                                    
                                    ], ), ), ), 
                    map_type = permify_async.models.map_type.MapType(), 
                    function = permify_async.models.function_type.FunctionType(), 
                    message_type = '', 
                    type_param = '', 
                    error = permify_async.models.error.error(), 
                    abstract_type = permify_async.models.abstract_type.AbstractType(
                        name = '', ), ),
                error = permify_async.models.error.error(),
                abstract_type = permify_async.models.abstract_type.AbstractType(
                    name = '', 
                    parameter_types = [
                        permify_async.models.v1alpha1/type.v1alpha1.Type(
                            dyn = permify_async.models.dyn.dyn(), 
                            null = '', 
                            primitive = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                            wrapper = 'PRIMITIVE_TYPE_UNSPECIFIED', 
                            well_known = 'WELL_KNOWN_TYPE_UNSPECIFIED', 
                            list_type = permify_async.models.list_type.ListType(
                                elem_type = permify_async.models.v1alpha1/type.v1alpha1.Type(
                                    dyn = permify_async.models.dyn.dyn(), 
                                    null = '', 
                                    map_type = permify_async.models.map_type.MapType(
                                        key_type = , 
                                        value_type = , ), 
                                    function = permify_async.models.function_type.FunctionType(
                                        result_type = , 
                                        arg_types = [
                                            
                                            ], ), 
                                    message_type = '', 
                                    type_param = '', 
                                    type = , 
                                    error = permify_async.models.error.error(), ), ), 
                            map_type = permify_async.models.map_type.MapType(), 
                            function = permify_async.models.function_type.FunctionType(), 
                            message_type = '', 
                            type_param = '', 
                            type = , 
                            error = permify_async.models.error.error(), )
                        ], )
            )
        else:
            return V1alpha1Type(
        )
        """

    def testV1alpha1Type(self):
        """Test V1alpha1Type"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
